-- Dados reais exportados do Supabase (via dump SQL fornecido) em seed.sql
-- Gerado automaticamente a partir da estrutura enviada pelo usuário.

INSERT INTO site_meta (id, key, value, inserted_at) VALUES ('2ce06308-561c-46e9-9a00-1c3f1de54364', 'header', '{"menu": ["O que é", "O que oferecemos", "Utilizar os equipamentos", "Requisitos", "Eventos", "Documentos", "Docentes", "Bolsistas"], "site_name": "FLUI — Fab Lab Universitário de Inovação do IFMG Ibirité", "primary_actions": ["Uso", "Empréstimo"]}', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO site_meta (id, key, value, inserted_at) VALUES ('ad371a40-7064-4653-aa1b-b4ef6b933b0f', 'hero', '{"cta": ["Conhecer o FLUI", "Solicitar para eventos"], "title": "FLUI — Ambiente de Inovação", "subtitle": "Um espaço de prototipagem rápida para transformar ideias em protótipos reais e funcionais — com foco em ensino, pesquisa, extensão e eventos."}', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO site_meta (id, key, value, inserted_at) VALUES ('b52a419c-d748-4ee2-80fa-72592997668c', 'about', '{"title": "O que é o FLUI?", "description": "O Fab Lab Universitário de Inovação é um laboratório de fabricação digital do IFMG Ibirité. Oferecemos um espaço de inovação onde estudantes e pesquisadores podem transformar ideias teóricas em protótipos reais e funcionais."}', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO site_meta (id, key, value, inserted_at) VALUES ('9db1acc3-274c-4ef4-a89c-a0cd7336b6c6', 'access', '{"contact": "flui.ibirite@ifmg.edu.br", "events_rule": "Caso seja para eventos sem meio de comprovação pelo SUAP: o professor ou servidor responsável deve formalizar o pedido.", "who_can_use": "Estudantes que estejam desenvolvendo atividades acadêmicas formais, como projeto de extensão, pesquisa, ensino ou eventos."}', '2026-08-25T20:08:39.603719+00:00');

INSERT INTO services (id, title, description, image_path, position, inserted_at) VALUES ('ffaa7946-52c3-4ed3-a5c8-58f1abb02b00', 'Corte a laser', 'Produção e corte de peças com precisão para protótipos e componentes.', 'assets/cortealaser.jpeg', 1, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO services (id, title, description, image_path, position, inserted_at) VALUES ('15912f59-dfe6-416a-967d-9eac14f6731c', 'Impressoras 3D', 'Modelagem e fabricação aditiva para peças, encaixes e validações rápidas.', 'assets/impressora3D.jpeg', 2, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO services (id, title, description, image_path, position, inserted_at) VALUES ('09f9e8b9-0e3e-41b3-8554-d2ef0cab918e', 'Impressora', 'Impressões para realização de apresentações, sinalização e materiais de apoio.', 'assets/impressora.jpeg', 3, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO services (id, title, description, image_path, position, inserted_at) VALUES ('d88c4c1c-f9cf-4dad-a3c1-cadc00303f8b', 'Plotter', 'Recortes e impressão de grande formato para projetos visuais e sinalização.', 'assets/plotter.jpeg', 4, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO services (id, title, description, image_path, position, inserted_at) VALUES ('195a8dc6-52a7-46dc-a7f0-83dd0404471d', 'Suporte a projetos', 'Apoio no desenvolvimento e na prototipagem para iniciativas acadêmicas e eventos.', 'assets/suporteaprojetos.jpeg', 5, '2026-08-25T20:08:39.603719+00:00');

INSERT INTO projects (id, title, subtitle, body, image_path, partners, inserted_at) VALUES ('0df8e13f-7261-4907-a5b1-705e8048ea36', 'Projeto Conecta Ibirité', 'Rede inteligente para conectar estudantes ao ecossistema produtivo de Ibirité', '{"ai": {"natural_language_search": "Tradução de critérios comuns de contratação em filtros estruturados e otimizados por similaridade.", "semantic_standardization": "Processamento automatizado de currículos para extrair uma taxonomia limpa de hard e soft skills."}, "intro": "Rede inteligente para conectar estudantes ao ecossistema produtivo de Ibirité, utilizando Modelos de Linguagem de Grande Escala (LLMs) para eliminar assimetrias de informação e otimizar a contratação local.", "methodology": [{"text": "Alinhamento institucional e validação com os parceiros públicos e comerciais.", "phase": 1}, {"text": "Aplicação de formulários customizados (Google Forms) para mapeamento imediato de demandas.", "phase": 2}, {"text": "Campanha massiva de divulgação focada especialmente nas 295 novas empresas abertas na cidade.", "phase": 3}, {"text": "Análise estatística de dados (CAGED/Caravela) combinada ao desenvolvimento da plataforma web definitiva.", "phase": 4}, {"text": "Desenvolvimento da plataforma web definitiva.", "phase": 5}], "partners_text": "Projeto de extensão desenvolvido pelo IFMG Campus Ibirité em cooperação mútua com a Câmara de Dirigentes Lojistas (CDL) e a Prefeitura Municipal de Ibirité.", "expected_results": ["Aumento expressivo na taxa de empregabilidade e inserção de discentes e egressos no mercado local.", "Redução de custos operacionais e tempo de recrutamento para o micro e pequeno empresário da região.", "Retenção de talentos e circulação de renda interna no município de Ibirité.", "Validação do ecossistema modular como Prova de Conceito (PoC) para futura expansão em rede para os demais campi do IFMG."]}', 'assets/logo-flui.png', '["CDL", "Prefeitura Municipal de Ibirité"]', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO projects (id, title, subtitle, body, image_path, partners, inserted_at) VALUES ('e85be92f-91e8-42fa-a6d4-95b857b4dcb6', 'Sistema DropEPI', 'Sistema de monitoramento e detecção automática de Equipamentos de Proteção Individual (EPIs) em tempo real', '{"intro": "Sistema de monitoramento e detecção automática de Equipamentos de Proteção Individual (EPIs) em tempo real, utilizando inteligência artificial aplicada à segurança do trabalho.", "stack": ["Python", "YOLOv8", "OpenCV", "Dataset customizado para ambiente laboratorial"], "computer_vision": "Avaliação e implementação de algoritmos de deep learning baseados na arquitetura YOLOv8 para o reconhecimento de múltiplos itens de segurança em ambientes de manufatura."}', 'assets/placeholder.jpeg', '[]', '2026-08-25T20:08:39.603719+00:00');

INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('071a7446-690d-43a1-a89d-a23b7a45bcc9', 'Carlos Dias da Silva Júnior', 'Pesquisador • Docente • Robótica, Sistemas Embarcados e Automação', 'Professor, pesquisador e desenvolvedor com atuação nas áreas de robótica, sistemas embarcados, automação industrial, eletrônica e desenvolvimento tecnológico aplicado à educação.', '{"about": "Desenvolve projetos de pesquisa, ensino e extensão voltados para robótica educacional, drones, visão computacional, sistemas inteligentes, automação e plataformas embarcadas.", "languages": ["Português (Fluente)", "Inglês (Intermediário)", "Espanhol (Básico/Intermediário)"], "experience": "Coordenação de projetos de robótica; pesquisas em sistemas embarcados e drones; atuação no ensino superior em Engenharia de Controle e Automação; orientação de IC e TCC.", "competencies": ["Robótica", "Sistemas Embarcados", "Automação Industrial", "Eletrônica", "Visão Computacional"], "recognitions": ["Menção Honrosa em Engenharias — X SIC IFMG 2022", "Orientador na Olimpíada Brasileira de Robótica"], "certifications": ["Cursos FIC JavaScript Básico/Avançado", "Operador e Programador de Sistemas Automatizados com CLP", "GNU Octave aplicado à Engenharia"]}', 'assets/Carlos.jpg', 'docente', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('847d2db4-e519-40c8-8932-fe55b97b71e4', 'Luciana Emirena dos Santos Carneiro', 'Doutora em Ciência da Informação • Gestão • Processos Organizacionais', 'Professora, pesquisadora e gestora com atuação nas áreas de Ciência da Informação, Administração, Gestão da Informação, Gestão do Conhecimento e Processos Organizacionais.', '{"about": "Atua no ensino superior, pesquisa aplicada e desenvolvimento institucional, com foco em inovação, gestão organizacional, transformação digital e integração entre educação e mercado de trabalho.", "education": ["Doutora em Ciência da Informação pela UFMG", "Mestre em Ciência da Informação", "Especialista em Gestão Estratégica da Informação"], "languages": ["Português (Fluente)", "Inglês (Avançado)", "Espanhol (Intermediário)", "Francês (Básico)"], "experience": "Coordenação de projetos empresa-escola; pesquisa em segurança da informação; processos organizacionais e indicadores de desempenho.", "competencies": ["Gestão da Informação", "Gestão do Conhecimento", "Planejamento Estratégico", "Segurança da Informação", "Gestão de Processos"], "recognitions": ["Placa de destaque acadêmico em Marketing Internacional (2006)", "Coordenação de projetos de integração empresa-escola"]}', 'assets/Luciana.jpg', 'docente', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('fb443151-5c52-49e8-8613-5e644202b6d3', 'Robert Luiz Gomes', 'Pesquisador • Docente • Design, Materiais e Inovação Tecnológica', 'Professor, pesquisador e designer com atuação nas áreas de design de produto, processos industriais, materiais, inovação tecnológica e desenvolvimento de soluções aplicadas.', '{"about": "Desenvolve projetos voltados para design sistêmico, materiais cerâmicos, polímeros, compósitos, design para ambientes e inovação aplicada à indústria e educação.", "experience": "Coordenação de projetos de pesquisa e extensão em design; desenvolvimento de produtos cerâmicos e compósitos; pesquisas financiadas pela FAPEMIG.", "competencies": ["Design de Produto", "Processos Industriais", "Materiais Compósitos", "Prototipagem", "Design Sistêmico"], "recognitions": ["1º colocado no concurso público IFMG (Edital 149/2014)", "Finalista do 2º Prêmio Sebrae Minas Design (Projeto AlumSlate)", "Patente junto ao INPI"]}', 'assets/Robert.jpeg', 'docente', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('35638fe3-5917-4684-a03e-29c3f52b6a26', 'Mateus Andrade Ferreira', 'Pesquisador • Docente • Energia, Automação e Sistemas Elétricos', 'Professor, pesquisador e engenheiro eletricista com atuação nas áreas de sistemas elétricos de potência, automação industrial, energias renováveis e educação tecnológica.', '{"about": "Professor EBTT no IFMG Ibirité, coordenador do curso técnico em Eletrotécnica e membro do Comitê Gestor do FLUI.", "education": ["Mestre em Engenharia Elétrica pelo CEFET-MG", "Especialista em Automação Industrial", "Engenheiro eletricista pela PUC Minas"], "experience": "Coordenação do curso de Eletrotécnica; Comitê Gestor do FLUI; projetos de energia solar fotovoltaica.", "competencies": ["Sistemas Elétricos", "Energia Solar Fotovoltaica", "Automação Industrial", "Qualidade da Energia", "Robótica Educacional"], "certifications": ["Especialização em Sistemas Eletroeletrônicos", "NR-10", "Capacitação em Sistemas Fotovoltaicos"]}', 'assets/Mateus.jpg', 'docente', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('180e9a54-ae36-4e18-a65d-99536d1ae11c', 'Edson Antunes Quaresma Júnior', 'Pesquisador • Docente • Gestão, Educação e Inovação', 'Professor, pesquisador e orientador acadêmico com atuação nas áreas de Administração, Educação Profissional e Tecnológica, Empreendedorismo, Gestão Educacional e Estudos Organizacionais.', '{"about": "Pesquisas em inovação educacional, integração curricular, gestão democrática e empreendedorismo social.", "languages": ["Português (Fluente)", "Inglês (Fluente)", "Francês (Fluente)", "Espanhol (Intermediário)", "Chinês (Básico)"], "experience": "Coordenação de projetos tecnológicos; produção científica internacional; desenvolvimento regional.", "competencies": ["Gestão Educacional", "Pesquisa Científica", "Inovação Pedagógica", "Extensão Universitária", "Organizações"], "recognitions": ["Prêmio Técnico Empreendedor SEBRAE (2010)", "Prêmio Excelência Acadêmica FUCAPE (2009)", "Prêmios de melhor trabalho em congressos"]}', 'assets/Edson.jpeg', 'docente', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('a7075d1d-8766-4325-b33e-fff89b2a969a', 'Bruna Camila Gomes Pereira', 'Estudante de Ciência da Computação', 'Estudante de Graduação em Ciência da Computação no IFMG e técnica em Administração pela FHA.', '{"about": "Atua ativamente nas iniciativas do ecossistema de inovação do FabLab FLUI.", "education": ["Bacharelado em Ciência da Computação (2025 — Atual) pelo IFMG", "Técnico em Administração (2024) pela FHA"], "experience": "Participação ativa no FLUI; gestão de projetos; Empresa Simulada (FHA); estudos em Redes Neurais para aproximação de funções.", "competencies": ["Gestão de Projetos", "Excel Intermediário", "Administração", "Redes Neurais Artificiais"], "certifications": ["Excel Básico/Intermediário (Fundação Bradesco)", "Introdução à Gestão de Projetos (IFMG)", "Redes Neurais (IFMG)"]}', 'assets/Bruna.jpeg', 'bolsista', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('d2813bab-1e92-47f5-8977-15604e48aa95', 'Eduarda Stephanne', 'Estudante de Engenharia de Controle e Automação', 'Estudante de Engenharia de Controle e Automação no IFMG e técnica em Automação.', '{"education": ["Bacharelado em Engenharia de Controle e Automação (2025 — 2030)", "Técnico em Automação (2022 — 2025) pelo IFMG"], "competencies": ["Industrial Automation", "Automatic Test Equipment", "Agile Methodologies"]}', 'assets/Eduarda.jpeg', 'bolsista', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('739897d1-b5da-4dfc-915a-ae8f6d9441ab', 'Kayky Yhudi de Souza Vidal', 'Estudante de Engenharia de Controle e Automação', 'Estudante de Engenharia de Controle e Automação, focado em automação e controle de processos organizacionais.', '{"education": ["Engenharia de Controle e Automação (2023 — Atual)", "Ensino Médio pelo IFMG"], "languages": ["Português (Nativo)", "Inglês (Razoável)", "Espanhol (Razoável)"], "competencies": ["Automação", "Controle de Processos"]}', 'assets/Kayky.jpeg', 'bolsista', '2026-08-25T20:08:39.603719+00:00');
INSERT INTO people (id, full_name, role, summary, details, image_path, type, inserted_at) VALUES ('88164905-7b77-404f-9bfb-7c64bd7b97c2', 'Pedro Brito Souza', 'Estudante de Engenharia de Controle e Automação', 'Estudante de Engenharia de Controle e Automação no IFMG e técnico em Mecatrônica.', '{"about": "Participa de iniciativas voltadas para desenvolvimento web front-end, prototipagem e integração com Inteligência Artificial Generativa.", "events": ["Encontro Nacional de Automação — 2025"], "experience": "Interfaces web funcionais; integração de dados industriais; soluções com IA Generativa no laboratório.", "competencies": ["Python", "Power BI", "Front-end", "Automação Industrial", "Prototipagem"], "recognitions": ["Aluno Nota 10 — 2023"], "certifications": ["Azure Machine Learning", "OpenAI no Azure", "Pneumática e CLP", "Liderança e Alta Performance", "Python Avançado"], "expanded_tech_skills": ["Azure AI", "OpenAI Services", "CLP", "Pneumática", "Pacote Office"]}', 'assets/Pedro.jpeg', 'bolsista', '2026-08-25T20:08:39.603719+00:00');

INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('b9efe850-78de-4e93-ad93-06637498bb7a', '071a7446-690d-43a1-a89d-a23b7a45bcc9', 1, 1, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('51adf0b5-61a4-42cd-ad69-e9b1a77e0c72', '847d2db4-e519-40c8-8932-fe55b97b71e4', 1, 2, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('9b03d70d-a0bb-4c79-a71b-2d517fcfa8e4', 'fb443151-5c52-49e8-8613-5e644202b6d3', 1, 3, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('01870213-131e-47a7-8c91-350cd7571ead', '35638fe3-5917-4684-a03e-29c3f52b6a26', 1, 4, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('64d8a4ae-0e8b-4ab5-815e-2c7af08cb1f4', '180e9a54-ae36-4e18-a65d-99536d1ae11c', 1, 5, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('60eaba30-2663-47d5-9ebe-666594df0616', 'a7075d1d-8766-4325-b33e-fff89b2a969a', 1, 6, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('91c2aac3-96ac-4b32-ad93-66ca137731e9', 'd2813bab-1e92-47f5-8977-15604e48aa95', 1, 7, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('6341b534-4494-4511-88a3-5832422a0669', '739897d1-b5da-4dfc-915a-ae8f6d9441ab', 1, 8, '2026-08-25T20:08:39.603719+00:00');
INSERT INTO team_members (id, person_id, visible, order_index, inserted_at) VALUES ('b0ccb982-555b-4d9f-85f3-4d6e80f885d8', '88164905-7b77-404f-9bfb-7c64bd7b97c2', 1, 9, '2026-08-25T20:08:39.603719+00:00');
